# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "minimal/trusty64"  

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "4096"

    config.vm.network "forwarded_port", guest: 9200, host: 9200
    config.vm.network "forwarded_port", guest: 9292, host: 9292

    #grid hub
    config.vm.network "forwarded_port", guest: 4444, host: 4444

    #grid node
    config.vm.network "forwarded_port", guest: 5555, host: 5555

    vb.customize ["modifyvm", :id, "--usb", "off"]
  end
end
